config/routes.rb
Tutorial::Application.routes.draw do
  resources :post_likes

  resources :microposts

  root :to => 'welcome#index'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  has_many :post_likes
  attr_accessible :body, :name
end

app/models/post_like.rb
class PostLike < ActiveRecord::Base
  attr_accessible :micropost_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/post_likes_controller.rb
class PostLikesController < ApplicationController
  # GET /post_likes
  # GET /post_likes.json
  def index
    @post_likes = PostLike.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_likes }
    end
  end

  # GET /post_likes/1
  # GET /post_likes/1.json
  def show
    @post_like = PostLike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_like }
    end
  end

  # GET /post_likes/new
  # GET /post_likes/new.json
  def new
    @post_like = PostLike.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_like }
    end
  end

  # GET /post_likes/1/edit
  def edit
    @post_like = PostLike.find(params[:id])
  end

  # POST /post_likes
  # POST /post_likes.json
  def create
    logger.error "=-=-=-=-=-=-=-=-=--=-=-=-=-==-=-=-=-=-=-=-"
    logger.error params[:micropost_id]
    @post_like = PostLike.create(:micropost_id => params[:micropost_id])
    logger.error "=-=-=-=-=-=-=-=-=--=-=-=-=-==-=-=-=-=-=-=-"
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  # PUT /post_likes/1
  # PUT /post_likes/1.json
  def update
    @post_like = PostLike.find(params[:id])

    respond_to do |format|
      if @post_like.update_attributes(params[:post_like])
        format.html { redirect_to @post_like, notice: 'Post like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_likes/1
  # DELETE /post_likes/1.json
  def destroy
    @post_like = PostLike.find(params[:id])
    @post_like.destroy

    respond_to do |format|
      format.html { redirect_to post_likes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @microposts = Micropost.all
    @micropost = Micropost.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.name %></td>
    <td><%= micropost.body %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @micropost.name %>
</p>

<p>
  <b>Body:</b>
  <%= @micropost.body %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/post_likes/_form.html.erb
<%= form_for(@post_like) do |f| %>
  <% if @post_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_like.errors.count, "error") %> prohibited this post_like from being saved:</h2>

      <ul>
      <% @post_like.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :micropost_id %><br />
    <%= f.number_field :micropost_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_likes/create.js.erb
$('#micropost_<%= @post_like.micropost_id %>').html("いいねしました");

app/views/post_likes/edit.html.erb
<h1>Editing post_like</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_like %> |
<%= link_to 'Back', post_likes_path %>

app/views/post_likes/index.html.erb
<h1>Listing post_likes</h1>

<table>
  <tr>
    <th>Micropost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_likes.each do |post_like| %>
  <tr>
    <td><%= post_like.micropost_id %></td>
    <td><%= link_to 'Show', post_like %></td>
    <td><%= link_to 'Edit', edit_post_like_path(post_like) %></td>
    <td><%= link_to 'Destroy', post_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post like', new_post_like_path %>

app/views/post_likes/new.html.erb
<h1>New post_like</h1>

<%= render 'form' %>

<%= link_to 'Back', post_likes_path %>

app/views/post_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Micropost:</b>
  <%= @post_like.micropost_id %>
</p>


<%= link_to 'Edit', edit_post_like_path(@post_like) %> |
<%= link_to 'Back', post_likes_path %>

app/views/welcome/index.html.erb
<h1>一行ブログ</h1>
<hr>

<ul>
  <% @microposts.each do |mp| %>
    <li>
      <span style="font-weight: bold;"><%= mp.name %></span>
      <%= truncate mp.body, :length => 10 %>
      <span id="micropost_<%= mp.id %>">
      <%= link_to 'いいね', post_likes_path(:micropost_id => mp.id), :method => :post, :remote => true %>
      </span>
      (<%= mp.post_likes.count %>)
    </li>
  <% end %>
</ul>